### ISSUE TITLE
so文件32 64位版本冲突?

### ISSUE THREAD

**Issue by shengyao15** [cundong/SmartAppUpdates#12]
我用了项目中自带的libApkPatchLibrary.so 文件, 放到服务器中执行的时候碰到的错误如下
查了下资料说是 jdk 版本冲突,  谁有没有64位的版本so文件?
```
[root@bogon apkPatch]# java -Djava.library.path=/public/service/apkPatch/so -jar apkDiff2.jar
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /public/service/apkPatch/so/libApkPatchLibrary.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /public/service/apkPatch/so/libApkPatchLibrary.so: /public/service/apkPatch/so/libApkPatchLibrary.so: 错误 ELF 类: ELFCLASS32 (Possible cause: architecture word width mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at com.cundong.apkdiff.ApkDiffDemo.<clinit>(ApkDiffDemo.java:32)
```

**Comment by lanpy233** [comment]
你解决了吗？

**Comment by lixiansky** [comment]
需要自己再次编译
